USE MASTER
IF EXISTS (SELECT * FROM SYS.DATABASES WHERE NAME = 'UPRIGHT')
    DROP DATABASE UPRIGHT
CREATE DATABASE UPRIGHT

USE UPRIGHT
CREATE TABLE UR_COMPANY(
	COMPANY_ID INT NOT NULL IDENTITY(1,1),
	COMPANY_NAME NVARCHAR(50) NULL,
    COMPANY_ADDRESS NVARCHAR(100) NULL,
    COMPANY_EMAIL NVARCHAR(50) NULL,
    COMPANY_PHONE1 NVARCHAR(20) NULL,
    COMPANY_PHONE2 NVARCHAR(20) NULL,
    COMPANY_ABN NVARCHAR(20) NULL,
    COMPANY_ACN NVARCHAR(20) NULL,
    CONSTRAINT PK_UR_COMPANY PRIMARY KEY CLUSTERED
    (
	    COMPANY_ID ASC
    )WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

CREATE TABLE UR_CONTACT(
	CONTACT_ID INT NOT NULL IDENTITY(1,1),
	CONTACT_NAME NVARCHAR(50) NULL,
    CONTACT_ADDRESS NVARCHAR(100) NULL,
    CONTACT_EMAIL NVARCHAR(50) NULL,
    CONTACT_PHONE1 NVARCHAR(20) NULL,
    CONTACT_PHONE2 NVARCHAR(20) NULL,
	COMPANY_ID INT NULL,
    CONSTRAINT PK_UR_CONTACT PRIMARY KEY CLUSTERED
    (
	    CONTACT_ID ASC
    )WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

CREATE TABLE UR_PRODUCT(
	PRODUCT_ID INT NOT NULL IDENTITY(1,1),
	COMPANY_ID INT NULL,
	PRODUCT_NAME NVARCHAR(255) NULL,
	PRODUCT_DESC NVARCHAR(MAX) NULL,
    CONSTRAINT PK_UR_PRODUCT PRIMARY KEY CLUSTERED
    (
	    PRODUCT_ID ASC
    )WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

CREATE TABLE UR_TRADE(
	TRADE_ID INT NOT NULL IDENTITY(1,1),
    COMPANY_ID INT NOT NULL,
    TRADE_TYPE INT NOT NULL,
    TRADE_INVOICE NVARCHAR(50) NOT NULL,
    TRADE_DATE DATETIME NOT NULL,
    TRADE_NOTE NVARCHAR(50) NOT NULL,
    CONSTRAINT PK_UR_TRADE PRIMARY KEY CLUSTERED
    (
	    TRADE_ID ASC
    )WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

CREATE TABLE UR_TRADE_PRODUCT(
	TRADE_ID INT NOT NULL,
	PRODUCT_ID INT NOT NULL,
    UNIT_PRICE FLOAT NOT NULL,
    QUANTITY INT NOT NULL,
    CONSTRAINT PK_UR_TRADE_PRODUCT PRIMARY KEY CLUSTERED
    (
	    TRADE_ID, PRODUCT_ID
    )WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

CREATE TABLE UR_DOCUMENT(
	DOCUMENT_ID INT NOT NULL IDENTITY(1,1),
    DOCUMENT_NAME NVARCHAR(50) NOT NULL,
    DOCUMENT_DESCRIPTION NVARCHAR(255) NULL,
	DOCUMENT_PATH NVARCHAR(255) NOT NULL,
    DOCUMENT_TYPE INT NOT NULL, --0: INVOICE, 1: CONTRACT, 2: PRODUCT DESCRIPTION, 3: OTHER
    DOCUMENT_CREATE_DT DATETIME NOT NULL,
    RELATED_OBJECT NVARCHAR(20) NULL,
    RELATED_ID INT NULL,
    CONSTRAINT PK_UR_DOCUMENT PRIMARY KEY CLUSTERED
    (
	    DOCUMENT_ID ASC
    )WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

CREATE TABLE UR_INVOICE(
	INVOICE_ID INT NOT NULL IDENTITY(1,1),
    INVOICE_NUMBER NVARCHAR(50) NOT NULL,
    TRADE_ID INT NOT NULL,
    CONSTRAINT PK_UR_INVOICE PRIMARY KEY CLUSTERED
    (
	    INVOICE_ID ASC
    )WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]